# EpicSuite - A micromanagement plugin for the EpicQuestz server
# An open-source project by StealWonders
# GitHub URL: https://github.com/StealWonders/EpicSuite
#
# Howdy mate! You've arrived at the configuration file, where things get a bit scary.
# If you would like to report a bug or suggest a feature,
# make sure to add an issue on the GitHub page for this plugin!
# Issue Tracker: https://github.com/StealWonders/EpicSuite/issues

resourcepacks:
  legacy:
    url: "https://downloads.epicquestz.com/files/ResourcePacks/EQPack_3.0.zip" # URL of the resource pack to download when using /rp
    hash: "90E81B922E60EEB82844CF1568C468F1847954DB" # Resource pack file hash to verify that the downloaded file is the correct one
  rohan:
    url: "https://downloads.epicquestz.com/files/ResourcePacks/Rohan/EQPack_Rohan-0.3.zip"
    hash: "f2cedb5a55239973b91ba26f4d1cd5025c23abf1"

tablist:
  header: "\n &2Epic&4Questz\n&7Welcome to the server {player}.\n" # Header of the tablist
  footer: "\n   &7Visit our website at www.epicquestz.com   \n " # Footer of the tablist

groups:
  creator:
    priority: 1
    color: DARK_RED
  admin:
    priority: 2
    color: GOLD
  default:
    priority: 3
    color: GRAY

# Messages that shall be broadcasted automatically every x minutes.
autobroadcast:
  delay: 8
  messages:
    - 'Want to join our build team & help us build Lord of The Rings maps? Read this article on how to apply for builder at &bhttps://tinyurl.com/y9jl6lyj'
    - 'Consider voting for our server to help us get new players! Use &b/vote'

votelinks:
  - "https://www.planetminecraft.com/server/epicquestz/vote/"
  - "https://minecraft-mp.com/server/270218/vote/"

donationurl: "https://ko-fi.com/epicquestz"

perks:
  Iron:
    pricing: "10€"
    perks:
      - "Receive in-game 'emote' commands"
      - "[Donor] tag on discord"
  Gold:
    pricing: "25€"
    perks:
      - "Access to custom join & leave messages"
  Emerald:
    pricing: "40€"
    perks:
      - "Access to the /tptoggle command to prevent other users from teleporting to you"
  Diamond:
    pricing: "55€"
    perks:
      - "Access to the via Discord bridged server chat"
  Obsidian:
    pricing: "70€+"
    perks:
      - "Special mention on Website & Discord"
      - "Ability to change your nickname"